"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FileText, Sparkles, User as UserIcon } from "lucide-react";
import type { Report } from "@/lib/types";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/status-badge";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";

function timeAgo(iso: string) {
  const mins = Math.round((Date.now() - new Date(iso).getTime()) / 60_000);
  if (mins < 60) return `${Math.max(mins, 1)}m ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

export default function ReportsPage() {
  const { projectId } = useParams<{ projectId: string }>();
  // TODO(graphql): empty placeholder until the GraphQL hook is wired.
  const reports = ([] as Report[]).sort(
    (a, b) => +new Date(b.updatedAt) - +new Date(a.updatedAt),
  );

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Reports</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Written summaries, generated by your team or by AI.
          </p>
        </div>
        <Button asChild>
          <Link href={`/projects/${projectId}/reports/new`}>New report</Link>
        </Button>
      </div>

      {reports.length === 0 ? (
        <Empty className="mt-6 border border-dashed border-border">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <FileText className="h-6 w-6" />
            </EmptyMedia>
            <EmptyTitle>No reports yet</EmptyTitle>
            <EmptyDescription>Create a report manually, or let the AI draft one.</EmptyDescription>
          </EmptyHeader>
          <Button variant="outline" asChild>
            <Link href={`/projects/${projectId}/reports/new`}>New report</Link>
          </Button>
        </Empty>
      ) : (
        <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
          {reports.map((report) => (
            <Link key={report.id} href={`/projects/${projectId}/reports/${report.id}`}>
              <Card className="h-full border-border bg-card p-5 transition-colors hover:border-primary/40">
                <div className="flex items-start justify-between gap-2">
                  <h3 className="font-semibold">{report.title}</h3>
                  <StatusBadge status={report.properties.status} />
                </div>
                <div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">
                  {report.properties.generatedByAI ? (
                    <>
                      <Sparkles className="h-3.5 w-3.5 text-primary" /> AI-generated
                    </>
                  ) : (
                    <>
                      <UserIcon className="h-3.5 w-3.5" /> Written by a team member
                    </>
                  )}
                  <span>· {timeAgo(report.updatedAt)}</span>
                </div>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
